services:
  train: 
    build: 
      context: .
      dockerfile: Dockerfile
    command: python model_training.py

  evaluation:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python model_evaluation.py

  serve:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "9000:9000"
    command: python model_serving.py
